# Generated by Django 6.0.3 on 2026-06-29 16:54

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Tiny Town Creations', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('about_text', models.TextField(blank=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('hero_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Store Configuration',
                'verbose_name_plural': 'Store Configuration',
            },
        ),
    ]
